"""Bounded SSE broker.

Lock order is fixed everywhere: operation barrier, then store lock, then broker lock.
Nothing awaits a socket while holding either lock, so a slow reader cannot stall a
mutation; its queue fills, the broker closes it, and the client reconnects with a cursor.
"""

from __future__ import annotations

import asyncio
import contextlib
from collections.abc import Sequence
from dataclasses import dataclass

from app.db.models import StoredEvent, parse_cursor


@dataclass(slots=True, eq=False)
class Subscriber:
    """One connected SSE client.

    Identity is the object, not its contents: two subscribers holding equal queues are
    still two different sockets, so ``eq=False`` keeps them distinct in the registry.
    """

    queue: asyncio.Queue[StoredEvent | None]
    closed: bool = False

    async def next_event(self, timeout: float) -> StoredEvent | None:
        """Return the next event, or ``None`` on heartbeat timeout / close."""
        try:
            return await asyncio.wait_for(self.queue.get(), timeout=timeout)
        except TimeoutError:
            return None


class EventBroker:
    """Fan-out with a bounded per-client queue and no unbounded buffering."""

    def __init__(self, queue_capacity: int) -> None:
        self._queue_capacity = queue_capacity
        self._lock = asyncio.Lock()
        self._subscribers: set[Subscriber] = set()

    @property
    def lock(self) -> asyncio.Lock:
        return self._lock

    @property
    def subscriber_count(self) -> int:
        return len(self._subscribers)

    async def register(self, replay: Sequence[StoredEvent]) -> Subscriber:
        """Register a subscriber whose queue is pre-filled with replayable events."""
        subscriber = Subscriber(queue=asyncio.Queue(maxsize=max(self._queue_capacity, len(replay) + 1)))
        for event in replay:
            subscriber.queue.put_nowait(event)
        async with self._lock:
            self._subscribers.add(subscriber)
        return subscriber

    async def unregister(self, subscriber: Subscriber) -> None:
        async with self._lock:
            self._subscribers.discard(subscriber)
        subscriber.closed = True

    async def publish(self, events: Sequence[StoredEvent]) -> None:
        """Deliver committed events. A full queue closes that client rather than blocking."""
        if not events:
            return
        async with self._lock:
            for subscriber in list(self._subscribers):
                for event in events:
                    try:
                        subscriber.queue.put_nowait(event)
                    except asyncio.QueueFull:
                        subscriber.closed = True
                        self._subscribers.discard(subscriber)
                        with contextlib.suppress(asyncio.QueueFull):
                            subscriber.queue.put_nowait(None)
                        break

    async def close_all(self) -> None:
        async with self._lock:
            for subscriber in list(self._subscribers):
                subscriber.closed = True
                with contextlib.suppress(asyncio.QueueFull):
                    subscriber.queue.put_nowait(None)
            self._subscribers.clear()


def replayable_events(
    *,
    events: Sequence[StoredEvent],
    stream_epoch: str,
    evicted_through: str,
    cursor: str | None,
) -> tuple[list[StoredEvent], bool]:
    """Resolve ``Last-Event-ID`` against the retained ring.

    Returns the events to replay and whether the cursor was servable. An unservable
    cursor makes the endpoint emit one id-less ``sync.required`` and close, which is the
    client's signal to take a fresh ``/sync-snapshot`` instead of guessing.
    """
    if cursor is None:
        return [], True

    parsed = parse_cursor(cursor)
    if parsed is None:
        return [], False
    cursor_epoch, cursor_revision, cursor_ordinal = parsed
    if cursor_epoch != stream_epoch:
        return [], False

    evicted = parse_cursor(evicted_through)
    if evicted is None or evicted[0] != stream_epoch:
        return [], False
    if (cursor_revision, cursor_ordinal) < (evicted[1], evicted[2]):
        return [], False

    replay = [event for event in events if _position(event) > (cursor_revision, cursor_ordinal)]
    return replay, True


def _position(event: StoredEvent) -> tuple[int, int]:
    parsed = parse_cursor(event["id"])
    if parsed is None:  # pragma: no cover - ids are generated by the store
        return (0, 0)
    return (parsed[1], parsed[2])
